---
title: "Course One Optional Final Project"
author: "Euan Mitchell"
date: "05/23/2025"
subtitle: "Investigation into Chicago taxis"
echo: false
bibliography: references.bib
format:
  html:
    embed-resources: true
---

## Packages

```{r}
#| label: packages
#| warning: false
#| message: false
library(tidyverse)
library(tidymodels)
library(scales)
```

```{r} 
#| label: glimpse
glimpse(taxi)
```

## Question 1

:::callout-note 
Qu. Is there a relationship between the distance (in miles) someone travels in a taxi and if they tip or not?
:::

```{r}
#| label: dist-tip-violin
ggplot(
  taxi, aes(x=tip, y=distance, color=tip)
) + geom_violin() +
  labs(
    title="Tipping as a function of distance",
    subtitle="Chicago taxi fare data",
    x="Tip",
    y="Distance (mi)",
    color="Tip",
  )
```

## Question 2

:::callout-note 
Qu. Do taxi passengers tend to tip more for the company Chicago Independents than the other companies?
:::

```{r}
#| label: tip-comp
taxi |>
  mutate(independent = if_else(
    company == "Chicago Independents", "yes", "no"
  )) |>
  ggplot(
    aes(x=independent, fill=tip)
  ) + geom_bar(position="fill")
```

## Your own question

:::callout-note
Qu. Is there any pattern in rates of tipping or distance ridden by day of the week?
:::

```{r}
#| label: my-qu-data
taxi |>
  group_by(dow) |>
  count(tip) |> 
  mutate(proportion = n / sum(n))
```
